<?php
/**
 * Russian Federation (RU) states/regions for WooCommerce.
 * English strings — переводы загружаются из .po/.mo темы (текст-домен codeweber).
 * ISO 3166-2:RU codes as keys.
 *
 * @package Codeweber
 */

defined( 'ABSPATH' ) || exit;

return array(
	'AD'  => __( 'Adygea', 'codeweber' ),
	'AL'  => __( 'Altai Republic', 'codeweber' ),
	'ALT' => __( 'Altai Krai', 'codeweber' ),
	'AMU' => __( 'Amur Oblast', 'codeweber' ),
	'ARK' => __( 'Arkhangelsk Oblast', 'codeweber' ),
	'AST' => __( 'Astrakhan Oblast', 'codeweber' ),
	'BA'  => __( 'Bashkortostan', 'codeweber' ),
	'BEL' => __( 'Belgorod Oblast', 'codeweber' ),
	'BRY' => __( 'Bryansk Oblast', 'codeweber' ),
	'BU'  => __( 'Buryatia', 'codeweber' ),
	'CE'  => __( 'Chechnya', 'codeweber' ),
	'CHE' => __( 'Chelyabinsk Oblast', 'codeweber' ),
	'CHU' => __( 'Chukotka Autonomous Okrug', 'codeweber' ),
	'CU'  => __( 'Chuvashia', 'codeweber' ),
	'DA'  => __( 'Dagestan', 'codeweber' ),
	'IN'  => __( 'Ingushetia', 'codeweber' ),
	'IRK' => __( 'Irkutsk Oblast', 'codeweber' ),
	'IVA' => __( 'Ivanovo Oblast', 'codeweber' ),
	'KB'  => __( 'Kabardino-Balkaria', 'codeweber' ),
	'KGD' => __( 'Kaliningrad Oblast', 'codeweber' ),
	'KL'  => __( 'Kalmykia', 'codeweber' ),
	'KLU' => __( 'Kaluga Oblast', 'codeweber' ),
	'KAM' => __( 'Kamchatka Krai', 'codeweber' ),
	'KC'  => __( 'Karachay-Cherkessia', 'codeweber' ),
	'KR'  => __( 'Karelia', 'codeweber' ),
	'KEM' => __( 'Kemerovo Oblast', 'codeweber' ),
	'KHA' => __( 'Khabarovsk Krai', 'codeweber' ),
	'KK'  => __( 'Khakassia', 'codeweber' ),
	'KHM' => __( 'Khanty-Mansi Autonomous Okrug', 'codeweber' ),
	'KIR' => __( 'Kirov Oblast', 'codeweber' ),
	'KO'  => __( 'Komi Republic', 'codeweber' ),
	'KOS' => __( 'Kostroma Oblast', 'codeweber' ),
	'KDA' => __( 'Krasnodar Krai', 'codeweber' ),
	'KYA' => __( 'Krasnoyarsk Krai', 'codeweber' ),
	'KGN' => __( 'Kurgan Oblast', 'codeweber' ),
	'KRS' => __( 'Kursk Oblast', 'codeweber' ),
	'LEN' => __( 'Leningrad Oblast', 'codeweber' ),
	'LIP' => __( 'Lipetsk Oblast', 'codeweber' ),
	'MAG' => __( 'Magadan Oblast', 'codeweber' ),
	'ME'  => __( 'Mari El', 'codeweber' ),
	'MO'  => __( 'Mordovia', 'codeweber' ),
	'MOS' => __( 'Moscow Oblast', 'codeweber' ),
	'MOW' => __( 'Moscow', 'codeweber' ),
	'MUR' => __( 'Murmansk Oblast', 'codeweber' ),
	'NEN' => __( 'Nenets Autonomous Okrug', 'codeweber' ),
	'NIZ' => __( 'Nizhny Novgorod Oblast', 'codeweber' ),
	'NGR' => __( 'Novgorod Oblast', 'codeweber' ),
	'NVS' => __( 'Novosibirsk Oblast', 'codeweber' ),
	'OMS' => __( 'Omsk Oblast', 'codeweber' ),
	'ORE' => __( 'Orenburg Oblast', 'codeweber' ),
	'ORL' => __( 'Oryol Oblast', 'codeweber' ),
	'PNZ' => __( 'Penza Oblast', 'codeweber' ),
	'PER' => __( 'Perm Krai', 'codeweber' ),
	'PRI' => __( 'Primorsky Krai', 'codeweber' ),
	'PSK' => __( 'Pskov Oblast', 'codeweber' ),
	'ROS' => __( 'Rostov Oblast', 'codeweber' ),
	'RYA' => __( 'Ryazan Oblast', 'codeweber' ),
	'SA'  => __( 'Sakha (Yakutia)', 'codeweber' ),
	'SAK' => __( 'Sakhalin Oblast', 'codeweber' ),
	'SAM' => __( 'Samara Oblast', 'codeweber' ),
	'SPE' => __( 'Saint Petersburg', 'codeweber' ),
	'SAR' => __( 'Saratov Oblast', 'codeweber' ),
	'SE'  => __( 'North Ossetia–Alania', 'codeweber' ),
	'SMO' => __( 'Smolensk Oblast', 'codeweber' ),
	'STA' => __( 'Stavropol Krai', 'codeweber' ),
	'SVE' => __( 'Sverdlovsk Oblast', 'codeweber' ),
	'TAM' => __( 'Tambov Oblast', 'codeweber' ),
	'TA'  => __( 'Tatarstan', 'codeweber' ),
	'TOM' => __( 'Tomsk Oblast', 'codeweber' ),
	'TUL' => __( 'Tula Oblast', 'codeweber' ),
	'TVE' => __( 'Tver Oblast', 'codeweber' ),
	'TYU' => __( 'Tyumen Oblast', 'codeweber' ),
	'TY'  => __( 'Tuva', 'codeweber' ),
	'UD'  => __( 'Udmurtia', 'codeweber' ),
	'ULY' => __( 'Ulyanovsk Oblast', 'codeweber' ),
	'VLA' => __( 'Vladimir Oblast', 'codeweber' ),
	'VGG' => __( 'Volgograd Oblast', 'codeweber' ),
	'VLG' => __( 'Vologda Oblast', 'codeweber' ),
	'VOR' => __( 'Voronezh Oblast', 'codeweber' ),
	'YAN' => __( 'Yamalo-Nenets Autonomous Okrug', 'codeweber' ),
	'YAR' => __( 'Yaroslavl Oblast', 'codeweber' ),
	'YEV' => __( 'Jewish Autonomous Oblast', 'codeweber' ),
	'ZAB' => __( 'Zabaykalsky Krai', 'codeweber' ),
	'CR'  => __( 'Republic of Crimea', 'codeweber' ),
	'SEV' => __( 'Sevastopol', 'codeweber' ),
	'DNR' => __( 'Donetsk People\'s Republic', 'codeweber' ),
	'LNR' => __( 'Luhansk People\'s Republic', 'codeweber' ),
	'ZAP' => __( 'Zaporizhzhia Oblast', 'codeweber' ),
	'KHE' => __( 'Kherson Oblast', 'codeweber' ),
);
